---
apiVersion: apps/v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e
  template:
    metadata:
      labels:
        app: e
    spec:
      containers:
        - name: e
          image: quay.io/stefanprodan/podinfo:3.0.0
          ports:
            - containerPort: 3000
